### ISSUE TITLE
REGEX errors

### ISSUE THREAD

**Issue by hackmonker** [markfeit/duplicacy-scripts#6]
For some reason I cant restore my backup as it gives a regex error. it might be due to some silly thing that I am missing, but still cant get my head around it.

```REGEX+=T(2[0-3]|[01][0-9]):[0-5][0-9]$: not found```

this error keeps popping up when I use

$DIR/bin/restore --storage drive1 --time 2021-07-02T15:59 /

what is the mistake in this command?

$DIR/bin/restore --storage drive1 --list does return a list of backups so it should be possible to restore. any clues?

**Comment by markfeit** [comment]
That's a bug.

Normally, I write shell scripts to comply with POSIX so they run correctly on as many shells as possible.  It appears that I let a BASH-ism slip through and the shell on your system doesn't understand it.  That's been corrected.  Running `$DEST/bin/update` will pull the latest from GitHub and install it.

**Comment by hackmonker** [comment]
it working as expected now. thanks a lot
