### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by hackmonker** [markfeit/duplicacy-scripts#7]
Right now root is the default for me which is /

Now I wanted to backup
/opt/folder1 and /home/user/folder2 only

I believe filter is what is required here. But when I use

```
+/opt/folder1
+/home/user/folder2
```
nothing is backed up, but when I use

```
+/opt
+/home
```

both folders are backed up. How do I specify only folder 1 and folder 2?

**Comment by markfeit** [comment]
This is a question about Duplicacy, not these scripts.

See the following:

 * https://github.com/gilbertchen/duplicacy/wiki/Include-Exclude-Patterns
 * https://forum.duplicacy.com/t/filters-include-exclude-patterns/1089

**Comment by hackmonker** [comment]
Yeah I saw but I just hoped you would shed some light on what was wrong in my filters. Well thanks anyway
