### ISSUE TITLE
Install Issue 'cp: -r not specified; omitting directory 'duplicacy''

### ISSUE THREAD

**Issue by airmarshall** [markfeit/duplicacy-scripts#8]
Sorry for being a complete novice. 

I'm sure I'm following the instructions to the letter but I can't for the life of me get the `make install` command to complete successfully. Output below:

```
root@nuc-smarthomehub ~/duplicacy-scripts# make install                                        
rm -rf test test/root
find . -name "*~" | xargs rm -f
rm -f /opt/duplicacy/bin/duplicacy
cp -fp duplicacy /opt/duplicacy/bin/duplicacy
cp: -r not specified; omitting directory 'duplicacy'
make: *** [Makefile:68: /opt/duplicacy/bin/duplicacy] Error 1
root@nuc-smarthomehub ~/duplicacy-scripts# 
```
Within the github clone directory I did:

`mkdir duplicacy` and placed in there the downloaded binary `duplicacy_linux_x64_2.7.2`

**Comment by markfeit** [comment]
The binary needs to be named `duplicacy` and it should be placed in the `duplicacy-scripts` directory.

I've changed the instructions to make that clearer.

**Comment by airmarshall** [comment]
Thank you, got it!
