### ISSUE TITLE
Help with restore command

### ISSUE THREAD

**Issue by airmarshall** [markfeit/duplicacy-scripts#9]
I'm trying to restore my repository to a DIR to test the backup integrity. But I'm struggling with the PATH variable.

If I want to restore the whole $ROOT backup as defined by the install command to another directory what should be command look like?

I've tried many iterations but the output is always the same:

```
root@nuc-smarthomehub .../duplicacy/bin# ./restore --dest /tmp/restore/ root 
Restoring from revision 1 as of 2021-10-05T22:37 from default
Restoring to /tmp/restore/
Storage set to gcd://Vault/nuc-smarthomehub-backups
Loaded 1 include/exclude pattern(s)
Forcing in-place mode with a non-default preference path
Parsing filter file /usr/bin/duplicacy/prefs/filters
Loaded 0 include/exclude pattern(s)
Restoring /tmp/restore to revision 1
Restored /tmp/restore to revision 1
Files: 0 total, 0 bytes
Downloaded 0 file, 0 bytes, 0 chunks
Skipped 0 file, 0 bytes
Total running time: 00:00:01
```
Thanks in advance!

**Comment by markfeit** [comment]
Any argument that isn't a path in the backup is passed directly to Duplicacy as a filter for selecting files from the snapshot.  A `+`  should get you everything:
```
./restore --dest /tmp/restore +
```
